* Chapter 1
** Danger: nature at work
We are used to seeing on our televison screens the battered remains of
cities pounded by earthquakes or the thousands of terrified refugees
escaping from yet another volcanic blast that they no longer hold any
surprise or fear for us, insulated as we are by distance and a lack of
true empathy.

我们经常在电视屏幕上看到地震将城市敲碎的残留，或者数以万计的难民在仓皇逃离
火山爆发时的麻木表情。由于距离的限制，我们对他们缺少了共情。

Although not entirely immune to disaster themselves, the great
majority of citizens fortunate enough to live in prosperous Europe,
North America, or Oceania view great natural catastrophes as
ephemeral events that occur in strange lands far, far away.

尽管灾难本身不能被免疫，对于well-developed的欧洲、北美和大洋洲的大部分
居民而言，自然界大型灾难被视作陌生的、遥远的区域发生的短暂事件。

Mildly interesting but only rarely impinging upon a daily existence
within which a murder in a popular soap opera or a win by the local
football team holds far more interest than 50,000 dead in a Venezuelan mudslide.

自然界所发生的灾难事件虽然会引起人们的关注，但在日常生活中产生的关注较
少。例如相较于委内瑞拉的造成了50,000人死亡的泥石流，人们更关注一场肥皂
剧中的谋杀案和当地球队取得了一场胜利。

Remarkably, such an attitude even prevails in regions of developed
countries that are also susceptible to volcanic eruptions and
earthquakes.

值得注意的是，上述这种态度在易出现火山爆发和地震的发达国家仍旧处于优势。

Talk to the citizens of Mammoth in California about the threat of
their local volcano exploding into life, or to the inhabitants of
Memphis, Tennessee, about prospects for their city being leveled by a
major quake, and they are likely to shrug and point out that they have
far more immediate things to worry about.

同California的Mammoth居民谈论当地火山爆发的威胁，或者同Tennessee的
Memphis的原住民关于该地区所处高地震等级，他们几乎都是耸着肩并且指出他
们有更直接的事情去担心，而不是担心这些灾难。

The only explanation is that these people are in denial. They are
quite aware that terrible disaster will strike at some point in the
future - they just can't accept that it might happen to them or their
descendants.

唯一的解释就是这些居民在否认。他们十分清楚的意识到这些可怕的灾难在未来
的某些时间点会发生。但他们不能接受灾难会发生在他们或他们的后代身上。
