* Chapter 1
** Danger: nature at work
We are used to seeing on our televison screens the battered remains of
cities pounded by earthquakes or the thousands of terrified refugees
escaping from yet another volcanic blast that they no longer hold any
surprise or fear for us, insulated as we are by distance and a lack of
true empathy.

我们经常在电视屏幕上看到地震将城市敲碎的残留，或者数以万计的难民在仓皇逃离
火山爆发时的麻木表情。由于距离的限制，我们对他们缺少了共情。

Although not entirely immune to disaster themselves, the great
majority of citizens fortunate enough to live in prosperous Europe,
North America, or Oceania view great natural catastrophes as
ephemeral events that occur in strange lands far, far away.

尽管灾难本身不能被免疫，对于well-developed的欧洲、北美和大洋洲的大部分
居民而言，自然界大型灾难被视作陌生的、遥远的区域发生的短暂事件。

Mildly interesting but only rarely impinging upon a daily existence
within which a murder in a popular soap opera or a win by the local
football team holds far more interest than 50,000 dead in a Venezuelan mudslide.

自然界所发生的灾难事件虽然会引起人们的关注，但在日常生活中产生的关注较
少。例如相较于委内瑞拉的造成了50,000人死亡的泥石流，人们更关注一场肥皂
剧中的谋杀案和当地球队取得了一场胜利。

Remarkably, such an attitude even prevails in regions of developed
countries that are also susceptible to volcanic eruptions and
earthquakes.

值得注意的是，上述这种态度在易出现火山爆发和地震的发达国家仍旧处于优势。

Talk to the citizens of Mammoth in California about the threat of
their local volcano exploding into life, or to the inhabitants of
Memphis, Tennessee, about prospects for their city being leveled by a
major quake, and they are likely to shrug and point out that they have
far more immediate things to worry about.

同California的Mammoth居民谈论当地火山爆发的威胁，或者同Tennessee的
Memphis的原住民关于该地区所处高地震等级，他们几乎都是耸着肩并且指出他
们有更直接的事情去担心，而不是担心这些灾难。

The only explanation is that these people are in denial. They are
quite aware that terrible disaster will strike at some point in the
future - they just can't accept that it might happen to them or their
descendants.

唯一的解释就是这些居民在否认。他们十分清楚的意识到这些可怕的灾难在未来
的某些时间点会发生。但他们不能接受灾难会发生在他们或他们的后代身上。



When it comes to natural catastrophes on a global scale such an
attitude is virtually omnipresent, pervading national governments,
international agencies, multinational trading blocks, and much of the
scientific community.

在如此全球范围的自然灾害面前，这种态度在国家政府、国际机构、跨国贸
易集团和许多科学团体中十分常见。

There is some cause for optimism, however, and in one area, at least,
this has begun to change. The threat to the Earth from asteroid and
comet impacts is now common knowledge and the race is on to identify
all those Earth-approaching asteroids that have potential to stop the
development of our race in its tracks.

这里有一些原因引发了这份乐观。然而至少在某一领域已经开始改变。从小行星
和彗星对地球带来的威胁已经成为普遍的常识，并且一场识别所有接近地球
的，有潜力停止我们人类发展的小行星的比赛已经开始。

Thanks to widely publicized television documentaries shown in the UK
and the United States, the added threats of volcanic super-eruptions
and giant tsunamis have now begun to reach an audience wider than the
tight groups of scientises that work on these rather esoteric phenomena.


鉴于UK和USA制作的广泛传播的电视纪录片，火山爆发和大海啸及其附加灾难已
经开始到达大众眼里而不是一小撮研究上述现象的科学家中。

In particular, the blanket media coverage of the December 2004 Asian
tsunami has ensured that the phenomenon and its capacity for
widespread devastation and loss of life is now understood and
appreciated far and wide.


而2004年亚洲海啸随着铺天盖地的媒体报导，也明确了由于生命和财产损失，它的现象和能力被广泛理解和认识。


In response, the UK Government is pushing for an international science
panel to evaluate potential natural threats on this scale, and plans
are well advanced for tsunami warning systems in both the Indian and
Atlantic Oceans.

作为回应的，UK政府正在推进一个用于评估自然风险潜在风险的国际科学专家咨
询组，并且在印度洋和大西洋的海啸预警系统在良好发展。

In face, the Earth is an extraordinarily fragile place that is fraught
with danger: a tiny rock hurtling through space, wracked by violent
movements of its curst and subject to dramatic climatic changes as its
geophysical and orbital circumstances vary.

事实上，地球是一个格外脆弱充满危险的的地方。一个小石头

Barely 10,000 years after the end of the Ice Age, the planet is
sweltering in some of the highest temperatures in recent Earth
history. At the same time, overpopulation and exploitation are
dramatically increasing the vulnerability of modern society to natural
catastrophes such as earthquakes, tsunamis, floods, and volcanic
eruptions.

仅在冰河世纪结束的10,000年以后，在最近的地球历史中，星球在一些最高温度
地区在变的更热。与此同时，人口过剩和剥削现象正在引人注目的增加现代社会
对例如地震、海啸、洪水和火山爆发等自然灾害的脆弱性。

In this introductory chapter, current threats to the planet and its
people are examined as a prelude to consideration of the bigger
threats to come.

在本章节，对地球和人类的当前危险被当作一个前奏去考虑即将到来的更大威
胁。


The Earth is the most dynamic planet in our solar system, and it is this
dynamism that has given us our protective magnetic field, our atmosphere,
our oceans, and ultimately our lives.

地球是太阳系中最具动力的行星，并且星球的这份动力给我们带来了保护性的磁场，
大气层、海洋和具有生命的人类。


The very same geophysical features that make the Earth so
life-giving and preserving also, however, make it dangerous.
For example, the spectacular volcanoes that in the early
history of our planet helped to generate the atmosphere and
the oceans have in the last three conturies wiped out a
quarter of a million people and injured countless others.

这些非常相似的地理特征使地球能够孕育生命，然而同样带来了危险。
例如，帮助早期地球产生大气层和海洋的壮观的火山，在最近的3个世
纪里已经夺取了两千五百万人类的生命并且造成了不可计数的人员受伤。

At the same time, the rains that feed our rivers and provide
us with the potable water that we need to survive have
devastated huge tracts of the planet with floods that in
recent years perhaps 20,000 were killed and tens of millions
affected by raging floodwaters, and in 1998 major rivers
floods in China and Bangladesh led to misery for literally
hundreds of millions of their inhabitants.

与此同时，降雨作为河流的水源向人类提供了生存必需的饮用水，以
洪水的形式破坏了地球的大量区域，正在近些年造成了20,000死亡
和数以亿计的影响。1998年中国和孟加拉国的洪水，向数以亿计的
居民带来的痛苦。

I could go on in the same vein, describing how lives made
enjoyable by a fresh fall of snow are swiftly ended when
it avalanches, or how a fresh breeze that sets sailing
dinghies skimming across the wave tops can soon transform
itself into a wailing banshee of terrible destruction - but
I think you get the picture.

继续按照脉络的，一场新鲜的降雪能够使大家变得开心，然而当雪
变为雪崩，或者一阵帮小船穿过浪头的微风转为一阵带来可怕迫害的
悲痛嚎叫的女妖。我认为你可以想象的到。

Nature provides us with all our needs but we must be very
wary of its rapidly changing moods.

大自然提供了我们所需的一切，但是我们必需非常警觉大自然的“情绪”
切换。

** The Eargh: a potted biography
The major global geophysical catastrophes that await us down
the line are in face just run-of-the-mill natural phenomena
writ large.

等待这我们的全球地理灾害仅仅是正常的自然现象。

In order to understand them, therefore, it is essential to
know a little about the Earth and how it functions.
为了理解他们，因此，懂得一点地球和地球是如何运转的是必需的。

Here, I will sashay through the 4.6 billion years of Earth
history, elucidating along the way those features that make
our world so hazardous and our future upon it so precarious.

这里，我们将浏览46亿年的地球历史，并沿着这条路阐明上述特征是
如何使我们的世界变得那么危险，以及我们的未来在其之上的不稳定性。

To begin, it is somethings worth pondering upon just how
incredibly old the Earth is, if only to appreciate the
notion that just because we have not experienced a
particular natural catastrophe before does not mean it
has never happened, nor that it will not happen again.

首先，地球的年龄是多么难以置信是一件值得思考的事情。


The Earth has been around just about long enough to ensure
that anything nature can conjure up it already has.

地球已经存在了足够长的时间，以至于确保了任何能召唤出的自然现象
都已发生。
